version: '3'
services:
  node:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/www/app
    environment:
      - NODE_ENV=development
    tty: true
    container_name: react-playground
